apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtms-grafana
  namespace: iamakamen-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtms-grafana
  template:
    metadata:
      labels:
        app: dtms-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          ports:
            - containerPort: 3000