apiVersion: v1
kind: ConfigMap
metadata:
  name: dtms-prometheus-config
  namespace: iamakamen-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "dtms_exporter"
        static_configs:
          - targets: ["exporter:8000"]

      - job_name: "dtms_anomaly_exporter"
        static_configs:
          - targets: ["anomaly:8001"]