global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'dtms_exporter'
    static_configs:
      - targets:
          - 'exporter-site-a:8000'
          - 'exporter-site-b:8000'
          - 'exporter-site-c:8000'

  - job_name: 'dtms_anomaly'
    static_configs:
      - targets: ['anomaly:8001']

  - job_name: 'dtms_streaming'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'spark-exporter:8002'
