apiVersion: v1
kind: Service
metadata:
  name: anomaly
  namespace: iamakamen-dev
spec:
  selector:
    app: dtms-anomaly
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP