apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: dtms
spec:
  selector:
    app: dtms-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP